CREATE TABLE certifications(
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    belt_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(belt_id) REFERENCES belts(id)
);